### ISSUE TITLE
plugin stopped working and disappeared from market. 

### ISSUE THREAD

**Issue by kjames2001** [saumya-banthia/tailscale-control#1]
plugin stopped working, showing only a sseperator. So I tried re-installing it, but it disappeared from decky market.

**Comment by saumya-banthia** [comment]
Fixed and pushed to the plugin repo. Thanks to @SimonT456 for helping. @kjames2001 feel free to raise a PR if it stops working the future, as this is a hobby project, therefore can sometimes be maintained on a lower priority.

Closing

**Comment by kjames2001** [comment]
Thanks! Noticed yesterday.
