### ISSUE TITLE
When multiple exit nodes are available unable to select a single exit node. 

### ISSUE THREAD

**Issue by DrunkenMurphy** [saumya-banthia/tailscale-control#10]
When there is more than one exit node available it shows both the IPs on a single line separated by a comma instead of separate selections. If you select the option that has both IPs it will show both of them as your selection then nothing happens when you turn on the exit node. Screenshots below to show the issue. 

I can disable one of the exit nodes and the plugin works as it should. 

![IMG_1495](https://github.com/saumya-banthia/tailscale-control/assets/155404535/1b3d8227-92cc-49c7-9dfe-17bc33438282)

![IMG_1496](https://github.com/saumya-banthia/tailscale-control/assets/155404535/953c0b76-2420-4f28-9db4-a3aa27eab766)

**Comment by saumya-banthia** [comment]
Will take a look. Thanks for bringing this up.

EDIT: Seems like a quick fix, was a typecasting flaw.

**Comment by saumya-banthia** [comment]
Fix has been pushed, raising PR.
