### ISSUE TITLE
QoL Improvements: Custom login server and up flags

### ISSUE THREAD

**Issue by pedxyuyuko** [saumya-banthia/tailscale-control#11]
### Context
I'm using Headscale instead of the official one, so I would like to have an entry to set it.   
My tailscale is already up before I use the plugin, so I just want to use the plugin to control it. However, the plugin always erases my login server setting.
Because that, I change the python script, but an update will easily remove the change.

Also, I'm running nobara instead of steamos, so make tailscale operator configureable is a good idea

### Usage
1. Go to the desktop and login to your headscale (``ts up --login-server`` and you have to register you machine using the login token)
2. ``ts down`` in Konsole
3. Go to the plugin and set you login-server again
4. Start Tailscale using the plugin toggle

English is not my first language and I just woke up.

**Comment by saumya-banthia** [comment]
Closing
