### ISSUE TITLE
Custom tailscale up command

### ISSUE THREAD

**Issue by mgundelfinger** [saumya-banthia/tailscale-control#13]
Hi! Thanks for creating this plugin, it's been really helpful and super easy to use!

I would like to add the --accept-routes option to my tailscale, and I can do so manually, in desktop mode, but i noticed in your code there is no regard for the options I manually added to my initial tailscale up command.

My idea would be to add a field in which we can add our own custom configuration, or simply a string of options that get appended to the tailscale up command.

What do you think?

**Comment by spfanning** [comment]
I would also like this feature for the `--ssh` option.

**Comment by pedxyuyuko** [comment]
maybe I can do it here: #12

**Comment by mgundelfinger** [comment]
> maybe I can do it here: #12

That would be great! It would surely be a hassle to add a toggle for every single option, but adding a field for a completely custom config would be a great start.

**Comment by pedxyuyuko** [comment]
> > maybe I can do it here: #12
> 
> That would be great! It would surely be a hassle to add a toggle for every single option, but adding a field for a completely custom config would be a great start.

Preview is here: https://github.com/saumya-banthia/tailscale-control/pull/12#issuecomment-1911818408

**Comment by mgundelfinger** [comment]
> Preview is here: https://github.com/saumya-banthia/tailscale-control/pull/12#issuecomment-1911818408

Sweet! Hope it gets merged soon!

**Comment by saumya-banthia** [comment]
Closing
