### ISSUE TITLE
Tailscale control does not work while the tailscaled.service is diabled

### ISSUE THREAD

**Issue by Vergil365** [saumya-banthia/tailscale-control#19]
If i disable the tailscaled.service and try to start tailscale with the tailscale control plugin, the toggle immediately turns back off.
I dont want to start it on every boot, just when i need it.
But right now it does not work for me.
I installed it via the recommended script from tailscale-dev and everything works fine, but the decky plugin is not able to start the service.
Every software is on the newest stable version (tailscale, decky loader, tailscale control, steamos).

**Comment by saumya-banthia** [comment]
At the moment I am AFK, will check this once I am back. Expect a bit of delay. Meanwhile if you are able to push a fix, please do.

**Comment by saumya-banthia** [comment]
@Vergil365 can you check and get back with the output of `tailscale status` when run in a terminal, in Desktop mode.
**Be sure to remove any info that is personally identifiable.**

EDIT: This plugin (as stated in the README) does not stop or start tailscaled.service - which would definitely require root privileges - which this plugin does not aim to do unless it becomes necessary. Even though tailscaled.service might be running it does not mean that tailscale is connected to the network, it's only when `tailscale up` is run that the service starts up the tunnel. 

EDIT 2: Just out of curiosity did a `ps aux` on tailscaled and it seems to use less than 0.5% of CPU and Memory resources (while down) - I know for some it can be an unneccessary 0.5%, but it does not seem enough for me to add root privileges to the plugin.

If I missed something, respond within a week on this thread - post which it will be closed.

**Comment by Vergil365** [comment]
sorry i thought tailscale control can stop/start the service. now that i turned the service on and tailscale control is disabled on boot, it is not connected, so everything works perfectly for me.
thank you for your anwser.

**Comment by saumya-banthia** [comment]
No worries. Closing.

**Comment by saumya-banthia** [comment]
No worries. Closing.
