### ISSUE TITLE
Compatibility with Nix Install

### ISSUE THREAD

**Issue by japzone1** [saumya-banthia/tailscale-control#7]
I'm working on getting Tailscale working on Steam Deck via Nix, and am the author of [this guide posted to Reddit](https://www.reddit.com/r/Tailscale/comments/183ppq1/steam_deck_using_nix_install_guide/?). Nix support was officially added in Steam OS 3.5, so no extra modifications are needed for it to work now. This new method of installing Tailscale on the Steam Deck using Nix has the advantage of persisting through Steam OS updates without relying on any Overlays that have to be updated/re-enabled after every OS update, and being installed without ever disabling the System Read-Only protection.

I've mostly been successful, with Tailscale persisting through reboots, and functioning as expected. But one thing that I haven't been able to figure out is that your Decky plugin doesn't seem to be able to see it or use it. I thought it might be permission or PATH troubles, but even after making sure the `tailscale` command works without root, and making sure it's in the PATH by adding the Nix binary path to `~/.bashrc`, it seems that Tailscale Control still can't see it. Other Decky plugins, like "Decky Terminal" can access and run the commands, but not yours.

I'm not familiar with how Decky's plugin system works, and my attempts to get any kind of debug log of possible errors from when Tailscale Control runs the tailscale commands have been unsuccessful. Do you have any ideas on where I should look to debug this?

**Comment by japzone1** [comment]
Ok, did some more testing using the "Bash Shortcuts" plugin and it seems that Steam Deck's Game mode does not load `.bashrc` and therefor the PATH doesn't get updated, like at all. The only directories in the PATH are `/usr/local/sbin:/usr/local/bin:/usr/bin` which means no user binaries are found by default. Only by directly running `$HOME/.nix-profile/bin/tailscale was I able to control tailscale.

I guess I can try modding the plugin with the direct path, but I was trying not to mess with the plugin itself. If only I could find where Game mode loads its PATH from.

**Comment by japzone1** [comment]
Yep, modding main.py to point to "/home/deck/.nix-profile/bin/tailscale" works.

**Comment by saumya-banthia** [comment]
Hey, I did not find a chance to use my Deck for some time now, therefore skipped to check if the plugin broke. Did you find a working fix? If so, it would be great if you can push that.

**Comment by japzone1** [comment]
> Hey, I did not find a chance to use my Deck for some time now, therefore skipped to check if the plugin broke. Did you find a working fix? If so, it would be great if you can push that.

The problem is that the PATH in Game mode doesn't include any user directories for some reason. Which means the Decky plugin can't find user installs of Tailscale(including Nix). I'm still trying to find somewhere where I can come up with a workaround to add the user directories to PATH in Game mode, but no luck so far. 

As for modding the plugin, I'm not familiar with Decky plugins much, and learning how will take a while with my limited free time. I have confirmed that manually editing the main.py to replace any "tailscale" with "/home/deck/.nix-profile/bin/tailscale" works to get the plugin working with the Nix install. But obviously you don't want to make that hard coded by default because then the plugin won't work with other install methods. So it'll be a while until I can make any kind of push for that myself. 

Alternative temp workarounds are to use the Bash Commands plugin to run Tailscale commands instead. 

Or you can still [use the old Tailscale install method](https://github.com/tailscale-dev/deck-tailscale) that uses a Systemd Overlay extension, which puts Tailscale at the system level so it's found in PATH in Game mode.

**Comment by saumya-banthia** [comment]
Looked into the plugin, seems to work with the current [official tailscale install guide for the deck](https://github.com/tailscale-dev/deck-tailscale) (@japzone1 you mentioned this does not persist across system updates in the reddit post, while the guide mentions that it does persist, is there something I might be missing?).

As of now I do not plan to support Nix based install (unless maybe if the official install is lacking the ability to persist across system updates, then I might look into it; but TBH I am more interested in creating a twingate plugin for deck). In the meantime, feel free to raise a PR if anyone is still interested in supporting. The way I would recommend is adding another toggle, which sends a command to a different backend function.

**Comment by japzone1** [comment]
> (@japzone1 you mentioned this does not persist across system updates in the reddit post, while the guide mentions that it does persist, is there something I might be missing?).

The current method uses Systemd Extension Overlays to place Tailscale into root directories without modifying the read-only System partition. However, due to how Valve has configured SteamOS, the extension has to be modified every time SteamOS is updated.[*(as they mention here)*](https://github.com/tailscale-dev/deck-tailscale#on-system-update) The method you linked to does provide a script which simplifies this, but it still means you have to rerun the script everytime SteamOS is updated, which can get particularly annoying if you're on the Preview channel. 

The Nix method is completely in User space though, and doesn't get affected at all by SteamOS updates.

I'm hoping to find somewhere to modify the System PATH for Game mode so that I don't have to touch your Plugin, but if I can't I'll have to find some free time to learn how Decky Plugins work. My Python skills are a bit rusty.

**Comment by saumya-banthia** [comment]
This should be fixed now, do open another issue if adding to path does not work (decky testers might be able to check). Closing.
